# Generated by Django 5.2.4 on 2025-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_livros_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
