# Generated by Django 5.2.4 on 2025-07-28 21:07
from django.utils.text import slugify
from django.db import migrations, models

def gerar_slugs_anteriores(apps, schema_editor):
    Livro = apps.get_model("livros", "Livro")
    for livro in Livro.objects.all():
        if not livro.slug:
            base_slug = slugify(livro.titulo)
            slug = base_slug
            contador = 1
            while Livro.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{contador}"
                contador += 1
            livro.slug = slug
            livro.save()

class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_opiniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='slug',
            field=models.SlugField(blank=True, null=True,  unique=True),
        ),
        migrations.RunPython(gerar_slugs_anteriores, reverse_code=migrations.RunPython.noop),
    ]
