# Generated by Django 5.2.4 on 2025-07-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_livro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='livros.livro'),
        ),
    ]
