# Generated by Django 5.2.9 on 2026-01-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_alter_opiniao_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
