# Generated by Django 5.2.9 on 2026-01-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
