# Generated by Django 5.2.9 on 2026-01-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_alter_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
